export const metadata = {
    title: 'Add Product Dashboard Next Hero',
    description: 'Generated by next hero',
  }


const AddProduct = () => {
    return (
        <div>
            AddProduct
        </div>
    );
};

export default AddProduct;