
export const metadata = {
    title: 'About Next Hero',
    description: 'Generated by next hero',
  }
const AboutPage = () => {
    return (
        <div>
            AboutPage
        </div>
    );
};

export default AboutPage;
