export const metadata = {
    title: 'Profile Next Hero',
    description: 'Generated by next hero',
  }

const ProfilePage = () => {
    return (
        <div>
            ProfilePage
        </div>
    );
};

export default ProfilePage;