export const metadata = {
    title: 'Dashboard Next Hero',
    description: 'Generated by next hero',
  }

const DashboardPage = () => {
    return (
        <div>
            DashboardPage
        </div>
    );
};

export default DashboardPage;